#!/usr/bin/env bash

# This is the magic path used by glick
BUNDLE_ROOT=/proc/self/fd/1023

exec_asm="Banshee.exe"
MONO_EXE="$BUNDLE_ROOT/lib/banshee/$exec_asm"
BANSHEE_EXEC_NAME=banshee

# Don't touch the real config directory
export XDG_CONFIG_HOME=$HOME/.config-glick
BANSHEE_CONFIG_DIR="$XDG_CONFIG_HOME/banshee-1"

export PATH=$BUNDLE_ROOT/bin${PATH:+:$PATH}
export LD_LIBRARY_PATH=$BUNDLE_ROOT/lib/banshee:$BUNDLE_ROOT/lib/banshee/Extensions:$BUNDLE_ROOT/lib/banshee/Backends:$BUNDLE_ROOT/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export GST_PLUGIN_PATH=/usr/lib/gstreamer-0.10:/usr/local/lib/gstreamer-0.10:$BUNDLE_ROOT/lib/banshee/gstreamer-0.10${GST_PLUGIN_PATH:+:$GST_PLUGIN_PATH}
export GST_REGISTRY="$BANSHEE_CONFIG_DIR/gstreamer-registry.bin"

[ -n "$BANSHEE_DEBUG" -o -f "${BANSHEE_CONFIG_DIR}/always-debug" ] && BANSHEE_DEBUG="--debug"
[ -n "$BANSHEE_TRACE" ] && BANSHEE_TRACE="--trace=$BANSHEE_TRACE"
[ -n "$BANSHEE_PROFILE" ] && BANSHEE_PROFILE="--profile=$BANSHEE_PROFILE"

for arg in $*; do
	case "x--debug" in ("x$arg")
		BANSHEE_DEBUG=$arg
	esac

	case "x--trace=" in ("x${arg:0:8}")
		BANSHEE_TRACE=$arg
	esac

	case "x--profile=" in ("x${arg:0:10}")
		BANSHEE_PROFILE=$arg
	esac

	case "x--redirect-log" in ("x$arg")
		[ -z "$(pidof $BANSHEE_EXEC_NAME)" ] && BANSHEE_REDIRECT_LOG="${BANSHEE_CONFIG_DIR}/log"
	esac

	case "x--client=" in ("x${arg:0:9}")
		BANSHEE_CLIENT="${arg:9}"
	esac

	case "x--use-bundled-theme" in ("x$arg")
		BANSHEE_BUNDLED_THEME="yes"
	esac
done

if [ ! -z "$BANSHEE_CLIENT" ]; then
	BANSHEE_CLIENT="--client=${BANSHEE_CLIENT}"
fi

# By default we use the bundled theme
GTK_THEME=Shiki-Brave
THEME_PREFIX=$BUNDLE_ROOT

if [ -z "$BANSHEE_BUNDLED_THEME" ]; then
	# Try to figure out if we're running in GNOME, and use the current theme
	GCONFTOOL=$(which gconftool || which gconftool-2)
	if [ x"$GCONFTOOL" != x"" ]; then
		GTK_THEME=$($GCONFTOOL --get /desktop/gnome/interface/gtk_theme)
		THEME_PREFIX=/usr
		echo "Trying to use the current GTK theme : $GTK_THEME"
	fi
fi
export GTK2_RC_FILES=${THEME_PREFIX}/share/themes/${GTK_THEME}/gtk-2.0/gtkrc

# Testing the SGen compacting GC, disabled for now
#export MONO_ENV_OPTIONS="--gc=sgen"

if [ -n "$BANSHEE_DEBUG" -o -n "$BANSHEE_TRACE" -o -n "$BANSHEE_PROFILE" ]; then
    MONO_OPTIONS="$BANSHEE_DEBUG $BANSHEE_TRACE $BANSHEE_PROFILE"
    echo "** Running Mono with $MONO_OPTIONS **"
fi

# Finally - environment is set up, time to run our beloved
exec_args="-a $BANSHEE_EXEC_NAME mono $MONO_OPTIONS $MONO_EXE $BANSHEE_DEBUG $BANSHEE_CLIENT"

if [ -z "$BANSHEE_REDIRECT_LOG" ]; then
	exec $exec_args "$@"
else
	mkdir -p `dirname "$BANSHEE_REDIRECT_LOG"`
	(echo "exec $exec_args " "$@"; echo; exec $exec_args "$@") &> $BANSHEE_REDIRECT_LOG
fi
