#!/usr/bin/env bash

# This is the magic path used by glick
BUNDLE_ROOT=/proc/self/fd/1023

exec_asm="Banshee.exe"
MONO_EXE="$BUNDLE_ROOT/lib/banshee/$exec_asm"
BANSHEE_EXEC_NAME=banshee

# Don't touch the real config directory
export XDG_CONFIG_HOME=$HOME/.config-glick
BANSHEE_CONFIG_DIR="$XDG_CONFIG_HOME/banshee-1"

export PATH=$BUNDLE_ROOT/bin${PATH:+:$PATH}
export LD_LIBRARY_PATH=$BUNDLE_ROOT/lib/banshee:$BUNDLE_ROOT/lib/banshee/Extensions:$BUNDLE_ROOT/lib/banshee/Backends:$BUNDLE_ROOT/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export GST_PLUGIN_PATH=/usr/lib/gstreamer-0.10:/usr/local/lib/gstreamer-0.10:$BUNDLE_ROOT/lib/banshee/gstreamer-0.10${GST_PLUGIN_PATH:+:$GST_PLUGIN_PATH}
export GST_REGISTRY="$BANSHEE_CONFIG_DIR/gstreamer-registry.bin"

# By default we use the bundled theme
GTK_THEME=Shiki-Brave
THEME_PREFIX=$BUNDLE_ROOT

# Try to figure out if we're running in GNOME, and use the current theme
GCONFTOOL=$(which gconftool || which gconftool-2)
if [ x"$GCONFTOOL" != x"" ]; then
	GTK_THEME=$($GCONFTOOL --get /desktop/gnome/interface/gtk_theme)
	THEME_PREFIX=/usr
fi
export GTK2_RC_FILES=${THEME_PREFIX}/share/themes/${GTK_THEME}/gtk-2.0/gtkrc

[ -n "$BANSHEE_DEBUG" -o -f "${BANSHEE_CONFIG_DIR}/always-debug" ] && BANSHEE_DEBUG="--debug"
BANSHEE_REDIRECT_LOG="${BANSHEE_CONFIG_DIR}/log"

# We are testing the SGen compacting GC
#export MONO_ENV_OPTIONS="--gc=sgen"

if [ -n "$BANSHEE_DEBUG" -o -n "$BANSHEE_TRACE" -o -n "$BANSHEE_PROFILE" ]; then
    MONO_OPTIONS="$BANSHEE_DEBUG $BANSHEE_TRACE $BANSHEE_PROFILE"
    echo "** Running Mono with $MONO_OPTIONS **"
fi

# Finally - environment is set up, time to run our beloved
exec_args="-a $BANSHEE_EXEC_NAME mono $MONO_OPTIONS $MONO_EXE $BANSHEE_DEBUG"

mkdir -p `dirname "$BANSHEE_REDIRECT_LOG"`
(echo "exec $exec_args " "$@"; echo; exec $exec_args "$@") &> $BANSHEE_REDIRECT_LOG

